### ISSUE TITLE
`npm install` で `404 Not Found: textlint-rule-hyogai-onkun@latest` エラーが表示される

### ISSUE THREAD

**Issue by shyazusa** [lostandfound/textlint-rule-hyogai-onkun#3]
npmのインストールでタイトルのエラーが出てしまいます。

```
$ npm install textlint-rule-hyogai-onkun
npm ERR! code E404
npm ERR! 404 Not Found: textlint-rule-hyogai-onkun@latest
```

npmのサイトで検索をしても`0 packages found for "textlint-rule-hyogai-onkun"`と表示されてしまいます。
[textlint-rule-hyogai-onkun - npm search](https://www.npmjs.com/search?q=textlint-rule-hyogai-onkun&page=1&ranking=optimal)

npmからのインストールは今後復活させる予定などはありますでしょうか。
ご確認をお願いいたします。 🙇

**Comment by azu** [comment]
Related issue: https://github.com/lostandfound/textlint-rule-ja-hiragana-daimeishi/issues/1

/cc @lostandfound

**Comment by shyazusa** [comment]
@azu 別のリポジトリで同じissueが起票されていたのですね。
ありがとうございます。

**Comment by lostandfound** [comment]
すみません。こちらのレポジトリは開発途上でした。
まだnpmにリリースしておらず、REAMEのインストールだけ先に書いてしまっていました。
辞書データの準備に時間が割けずリリースの予定は未定です。
ご面倒おかけしました。

**Comment by shyazusa** [comment]
@lostandfound 
承知いたしました。
ご返事ありがとうございます。

こちらのチケットはCloseさせて頂きますね。
